name: Auto-Clean

on:
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI (手动安装方法)
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
          gh --version

      - name: Delete older releases (保留最新的一个)
        run: |
          # 获取所有 releases，按创建时间排序（最新的在前）
          releases=$(gh release list --limit 100 | awk '{print $1}')
          
          # 跳过第一个（最新的）release，删除其余的
          first=true
          for release in $releases; do
            if [ "$first" = true ]; then
              echo "保留最新的 release: $release"
              first=false
            else
              echo "删除旧的 release: $release"
              gh release delete "$release" -y --delete-tag  # 如果你想保留标签，移除 --delete-tag
            fi
          done
          
          echo "清理完成：保留了最新的 release，删除了 $(echo "$releases" | wc -l) 个旧 release 中的 $(($(echo "$releases" | wc -l) - 1)) 个"
